-- PostgreSQL 15+
-- Relational object modeling for repository governance, Pull Requests,
-- Code Review, Approvals, and Branch Protection.

BEGIN;

DROP VIEW IF EXISTS pull_request_merge_eligibility;
DROP FUNCTION IF EXISTS evaluate_pull_request_merge(BIGINT);
DROP FUNCTION IF EXISTS guard_protected_branch_push();
DROP TABLE IF EXISTS merge_events CASCADE;
DROP TABLE IF EXISTS status_checks CASCADE;
DROP TABLE IF EXISTS review_comments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS review_requests CASCADE;
DROP TABLE IF EXISTS pull_request_labels CASCADE;
DROP TABLE IF EXISTS pull_requests CASCADE;
DROP TABLE IF EXISTS branch_protection CASCADE;
DROP TABLE IF EXISTS commits CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS repository_members CASCADE;
DROP TABLE IF EXISTS reviewers CASCADE;
DROP TABLE IF EXISTS repositories CASCADE;

CREATE TABLE repositories (
    repository_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner TEXT NOT NULL CHECK (btrim(owner) <> ''),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    default_branch TEXT NOT NULL CHECK (btrim(default_branch) <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (owner, name)
);

CREATE TABLE reviewers (
    reviewer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE CHECK (btrim(username) <> ''),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    can_review BOOLEAN NOT NULL DEFAULT TRUE,
    is_administrator BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE repository_members (
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id)
        ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES reviewers(reviewer_id)
        ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('READ', 'TRIAGE', 'WRITE', 'MAINTAIN', 'ADMIN')),
    can_bypass_protection BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (repository_id, reviewer_id)
);

CREATE TABLE branches (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id)
        ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    head_sha TEXT NOT NULL CHECK (btrim(head_sha) <> ''),
    protected BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    UNIQUE (repository_id, name)
);

CREATE TABLE commits (
    commit_sha TEXT PRIMARY KEY CHECK (btrim(commit_sha) <> ''),
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id)
        ON DELETE CASCADE,
    branch_id BIGINT REFERENCES branches(branch_id) ON DELETE SET NULL,
    author_id BIGINT REFERENCES reviewers(reviewer_id) ON DELETE SET NULL,
    committed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    message TEXT NOT NULL CHECK (btrim(message) <> ''),
    parent_shas TEXT[] NOT NULL DEFAULT '{}'
);

CREATE INDEX commits_repository_time_idx
    ON commits(repository_id, committed_at DESC);

CREATE TABLE branch_protection (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id)
        ON DELETE CASCADE,
    branch_name TEXT NOT NULL CHECK (btrim(branch_name) <> ''),
    required_approvals INTEGER NOT NULL DEFAULT 1
        CHECK (required_approvals >= 0),
    require_conversation_resolution BOOLEAN NOT NULL DEFAULT TRUE,
    require_linear_history BOOLEAN NOT NULL DEFAULT FALSE,
    restrict_direct_pushes BOOLEAN NOT NULL DEFAULT TRUE,
    restrict_force_pushes BOOLEAN NOT NULL DEFAULT TRUE,
    prevent_deletion BOOLEAN NOT NULL DEFAULT TRUE,
    dismiss_stale_approvals BOOLEAN NOT NULL DEFAULT TRUE,
    administrators_must_comply BOOLEAN NOT NULL DEFAULT TRUE,
    bypass_roles TEXT[] NOT NULL DEFAULT '{}',
    UNIQUE (repository_id, branch_name)
);

CREATE TABLE pull_requests (
    pull_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_id BIGINT NOT NULL REFERENCES repositories(repository_id)
        ON DELETE CASCADE,
    number INTEGER NOT NULL CHECK (number > 0),
    title TEXT NOT NULL CHECK (btrim(title) <> ''),
    description TEXT NOT NULL DEFAULT '',
    source_branch TEXT NOT NULL CHECK (btrim(source_branch) <> ''),
    target_branch TEXT NOT NULL CHECK (btrim(target_branch) <> ''),
    head_sha TEXT NOT NULL REFERENCES commits(commit_sha),
    base_sha TEXT NOT NULL REFERENCES commits(commit_sha),
    state TEXT NOT NULL DEFAULT 'OPEN'
        CHECK (state IN ('DRAFT', 'OPEN', 'CLOSED', 'MERGED')),
    has_conflicts BOOLEAN NOT NULL DEFAULT FALSE,
    merge_strategy TEXT CHECK (
        merge_strategy IS NULL OR
        merge_strategy IN ('MERGE_COMMIT', 'SQUASH', 'REBASE')
    ),
    merged_commit_sha TEXT REFERENCES commits(commit_sha),
    created_by BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    merged_at TIMESTAMPTZ,
    UNIQUE (repository_id, number),
    CHECK (source_branch <> target_branch),
    CHECK (
        (state = 'MERGED' AND merged_at IS NOT NULL AND merge_strategy IS NOT NULL)
        OR state <> 'MERGED'
    )
);

CREATE INDEX pull_requests_target_state_idx
    ON pull_requests(repository_id, target_branch, state);

CREATE INDEX pull_requests_head_sha_idx
    ON pull_requests(head_sha);

CREATE TABLE pull_request_labels (
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id)
        ON DELETE CASCADE,
    label TEXT NOT NULL CHECK (btrim(label) <> ''),
    PRIMARY KEY (pull_request_id, label)
);

CREATE TABLE review_requests (
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id)
        ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pull_request_id, reviewer_id)
);

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id)
        ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
    state TEXT NOT NULL CHECK (
        state IN ('PENDING', 'COMMENTED', 'APPROVED', 'CHANGES_REQUESTED', 'DISMISSED')
    ),
    commit_sha TEXT NOT NULL REFERENCES commits(commit_sha),
    body TEXT NOT NULL DEFAULT '',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    dismissed_at TIMESTAMPTZ,
    UNIQUE (pull_request_id, reviewer_id, review_id),
    CHECK (
        (state = 'DISMISSED' AND dismissed_at IS NOT NULL)
        OR state <> 'DISMISSED'
    )
);

-- Keep review history. Eligibility queries select the latest current decision
-- from each reviewer instead of counting every historical approval.
CREATE INDEX reviews_pr_reviewer_time_idx
    ON reviews(pull_request_id, reviewer_id, submitted_at DESC, review_id DESC);

CREATE INDEX reviews_state_commit_idx
    ON reviews(pull_request_id, state, commit_sha);

CREATE TABLE review_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id)
        ON DELETE CASCADE,
    review_id BIGINT REFERENCES reviews(review_id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
    file_path TEXT NOT NULL CHECK (btrim(file_path) <> ''),
    line_number INTEGER CHECK (line_number IS NULL OR line_number > 0),
    body TEXT NOT NULL CHECK (btrim(body) <> ''),
    is_inline BOOLEAN NOT NULL DEFAULT TRUE,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    CHECK (
        (resolved = TRUE AND resolved_at IS NOT NULL)
        OR resolved = FALSE
    )
);

CREATE INDEX unresolved_review_comments_idx
    ON review_comments(pull_request_id)
    WHERE resolved = FALSE;

CREATE TABLE status_checks (
    status_check_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id)
        ON DELETE CASCADE,
    check_name TEXT NOT NULL CHECK (btrim(check_name) <> ''),
    commit_sha TEXT NOT NULL REFERENCES commits(commit_sha),
    state TEXT NOT NULL CHECK (state IN ('QUEUED', 'IN_PROGRESS', 'SUCCESS', 'FAILURE', 'CANCELLED')),
    details TEXT NOT NULL DEFAULT '',
    completed_at TIMESTAMPTZ,
    UNIQUE (pull_request_id, check_name, commit_sha)
);

CREATE INDEX status_checks_pr_sha_idx
    ON status_checks(pull_request_id, commit_sha, check_name);

CREATE TABLE merge_events (
    merge_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(pull_request_id),
    actor_id BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
    strategy TEXT NOT NULL CHECK (strategy IN ('MERGE_COMMIT', 'SQUASH', 'REBASE')),
    result TEXT NOT NULL CHECK (result IN ('SUCCEEDED', 'REJECTED')),
    reason TEXT NOT NULL DEFAULT '',
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A trigger blocks direct branch-head changes when a protection policy
-- restricts direct pushes. Application roles should not own these tables.
CREATE OR REPLACE FUNCTION guard_protected_branch_push()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.head_sha IS DISTINCT FROM OLD.head_sha
       AND EXISTS (
           SELECT 1
           FROM branch_protection bp
           WHERE bp.repository_id = NEW.repository_id
             AND bp.branch_name = NEW.name
             AND bp.restrict_direct_pushes
       ) THEN
        RAISE EXCEPTION
            'Direct push to protected branch % is restricted', NEW.name;
    END IF;

    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
       AND EXISTS (
           SELECT 1
           FROM branch_protection bp
           WHERE bp.repository_id = NEW.repository_id
             AND bp.branch_name = NEW.name
             AND bp.prevent_deletion
       ) THEN
        RAISE EXCEPTION
            'Deletion of protected branch % is restricted', NEW.name;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER protected_branch_update_guard
BEFORE UPDATE OF head_sha, deleted_at ON branches
FOR EACH ROW
EXECUTE FUNCTION guard_protected_branch_push();

-- Evaluate the latest decision per reviewer. An approval is current only
-- when it applies to the current PR head and the reviewer remains eligible.
CREATE OR REPLACE FUNCTION evaluate_pull_request_merge(p_pr_id BIGINT)
RETURNS TABLE (
    pull_request_id BIGINT,
    merge_eligible BOOLEAN,
    eligible_approvals BIGINT,
    required_approvals INTEGER,
    blockers TEXT[]
)
LANGUAGE sql
STABLE
AS $$
    WITH pr AS (
        SELECT p.*, bp.required_approvals,
               bp.require_conversation_resolution,
               bp.dismiss_stale_approvals,
               bp.require_linear_history,
               bp.administrators_must_comply
        FROM pull_requests p
        LEFT JOIN branch_protection bp
          ON bp.repository_id = p.repository_id
         AND bp.branch_name = p.target_branch
        WHERE p.pull_request_id = p_pr_id
    ),
    latest_reviews AS (
        SELECT DISTINCT ON (r.reviewer_id)
            r.reviewer_id, r.state, r.commit_sha, r.pull_request_id
        FROM reviews r
        WHERE r.pull_request_id = p_pr_id
        ORDER BY r.reviewer_id, r.submitted_at DESC, r.review_id DESC
    ),
    approval_count AS (
        SELECT COUNT(*) AS total
        FROM latest_reviews lr
        JOIN reviewers rv ON rv.reviewer_id = lr.reviewer_id
        CROSS JOIN pr
        WHERE lr.state = 'APPROVED'
          AND rv.active
          AND rv.can_review
          AND (NOT COALESCE(pr.dismiss_stale_approvals, TRUE)
               OR lr.commit_sha = pr.head_sha)
    ),
    check_failures AS (
        SELECT COUNT(*) AS total
        FROM pr
        CROSS JOIN LATERAL unnest(
            COALESCE(
                ARRAY(
                    SELECT unnest(ARRAY[]::TEXT[])
                ),
                ARRAY[]::TEXT[]
            )
        ) AS unused(name)
    ),
    missing_checks AS (
        SELECT COUNT(*) AS total
        FROM pr
        WHERE EXISTS (
            SELECT 1
            FROM branch_protection bp
            WHERE bp.repository_id = pr.repository_id
              AND bp.branch_name = pr.target_branch
        )
    ),
    blockers AS (
        SELECT
            CASE
                WHEN pr.pull_request_id IS NULL THEN
                    ARRAY['Pull request not found']::TEXT[]
                ELSE
                    array_remove(ARRAY[
                        CASE WHEN pr.state <> 'OPEN'
                            THEN 'Pull request is not open' END,
                        CASE WHEN pr.state = 'DRAFT'
                            THEN 'Draft pull request cannot be merged' END,
                        CASE WHEN pr.has_conflicts
                            THEN 'Merge conflicts remain' END,
                        CASE WHEN pr.required_approvals IS NULL
                            THEN 'No branch protection policy exists' END,
                        CASE WHEN pr.required_approvals IS NOT NULL
                                  AND approval_count.total < pr.required_approvals
                            THEN 'Insufficient current eligible approvals' END,
                        CASE WHEN pr.require_conversation_resolution
                                  AND EXISTS (
                                      SELECT 1
                                      FROM review_comments rc
                                      WHERE rc.pull_request_id = pr.pull_request_id
                                        AND NOT rc.resolved
                                  )
                            THEN 'Unresolved review conversations remain' END,
                        CASE WHEN EXISTS (
                            SELECT 1
                            FROM branch_protection bp
                            CROSS JOIN LATERAL unnest(
                                ARRAY['unit-tests', 'security-scan']::TEXT[]
                            ) AS required(check_name)
                            WHERE bp.repository_id = pr.repository_id
                              AND bp.branch_name = pr.target_branch
                              AND NOT EXISTS (
                                  SELECT 1
                                  FROM status_checks sc
                                  WHERE sc.pull_request_id = pr.pull_request_id
                                    AND sc.check_name = required.check_name
                                    AND sc.commit_sha = pr.head_sha
                                    AND sc.state = 'SUCCESS'
                              )
                        )
                            THEN 'A required status check is missing or failing' END,
                        CASE WHEN EXISTS (
                            SELECT 1
                            FROM latest_reviews lr
                            JOIN reviewers rv ON rv.reviewer_id = lr.reviewer_id
                            CROSS JOIN pr p2
                            WHERE lr.state = 'CHANGES_REQUESTED'
                              AND rv.active AND rv.can_review
                              AND (
                                  NOT COALESCE(p2.dismiss_stale_approvals, TRUE)
                                  OR lr.commit_sha = p2.head_sha
                              )
                        )
                            THEN 'A current review requests changes' END
                    ]::TEXT[], NULL)
            END AS reasons
        FROM pr
        CROSS JOIN approval_count
    )
    SELECT
        p_pr_id,
        COALESCE(cardinality(blockers.reasons) = 0, FALSE),
        approval_count.total,
        pr.required_approvals,
        blockers.reasons
    FROM pr
    CROSS JOIN approval_count
    CROSS JOIN blockers;
$$;

-- A view exposes governance results without requiring every client to
-- duplicate the eligibility query.
CREATE VIEW pull_request_merge_eligibility AS
SELECT
    p.pull_request_id,
    r.owner || '/' || r.name AS repository,
    p.number,
    p.title,
    p.state,
    p.source_branch,
    p.target_branch,
    eligibility.merge_eligible,
    eligibility.eligible_approvals,
    eligibility.required_approvals,
    eligibility.blockers
FROM pull_requests p
JOIN repositories r ON r.repository_id = p.repository_id
CROSS JOIN LATERAL evaluate_pull_request_merge(p.pull_request_id) eligibility;

INSERT INTO repositories (repository_id, owner, name, default_branch)
VALUES
    (1, 'platform', 'payments-api', 'main');

INSERT INTO reviewers (
    reviewer_id, username, active, can_review, is_administrator
)
VALUES
    (1, 'mira', TRUE, TRUE, FALSE),
    (2, 'lee', TRUE, TRUE, FALSE),
    (3, 'sam', TRUE, TRUE, TRUE),
    (4, 'inactive-reviewer', FALSE, TRUE, FALSE);

INSERT INTO repository_members (
    repository_id, reviewer_id, role, can_bypass_protection
)
VALUES
    (1, 1, 'WRITE', FALSE),
    (1, 2, 'MAINTAIN', FALSE),
    (1, 3, 'ADMIN', TRUE),
    (1, 4, 'READ', FALSE);

INSERT INTO branches (branch_id, repository_id, name, head_sha, protected)
VALUES
    (1, 1, 'main', 'base-001', TRUE),
    (2, 1, 'feature/webhook-signatures', 'head-101', FALSE),
    (3, 1, 'feature/slow-query', 'head-102', FALSE);

INSERT INTO commits (commit_sha, repository_id, branch_id, author_id, message)
VALUES
    ('base-001', 1, 1, 3, 'Establish protected baseline'),
    ('head-101', 1, 2, 1, 'Validate webhook signatures'),
    ('head-102', 1, 3, 2, 'Improve query execution plan'),
    ('head-103', 1, 2, 1, 'Reject missing webhook headers');

INSERT INTO branch_protection (
    repository_id,
    branch_name,
    required_approvals,
    require_conversation_resolution,
    require_linear_history,
    restrict_direct_pushes,
    restrict_force_pushes,
    prevent_deletion,
    dismiss_stale_approvals,
    administrators_must_comply,
    bypass_roles
)
VALUES (
    1, 'main', 2, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, '{}'
);

INSERT INTO pull_requests (
    pull_request_id,
    repository_id,
    number,
    title,
    description,
    source_branch,
    target_branch,
    head_sha,
    base_sha,
    state,
    created_by
)
VALUES (
    101, 1, 101,
    'Validate webhook signatures',
    'Reject requests with missing or invalid signatures.',
    'feature/webhook-signatures',
    'main',
    'head-101',
    'base-001',
    'OPEN',
    1
), (
    102, 1, 102,
    'Optimize invoice lookup',
    'Reduce unnecessary database scans.',
    'feature/slow-query',
    'main',
    'head-102',
    'base-001',
    'DRAFT',
    2
);

INSERT INTO pull_request_labels (pull_request_id, label)
VALUES
    (101, 'security'),
    (101, 'backend'),
    (102, 'performance');

INSERT INTO review_requests (pull_request_id, reviewer_id)
VALUES
    (101, 1),
    (101, 2),
    (102, 1);

INSERT INTO reviews (
    review_id, pull_request_id, reviewer_id, state, commit_sha, body
)
VALUES
    (1001, 101, 1, 'APPROVED', 'head-101', 'Signature checks are correct.'),
    (1002, 101, 2, 'APPROVED', 'head-101', 'Failure cases are covered.'),
    (1003, 102, 1, 'COMMENTED', 'head-102', 'Please add query-plan evidence.');

INSERT INTO review_comments (
    comment_id, pull_request_id, review_id, author_id, file_path,
    line_number, body, is_inline, resolved, resolved_at
)
VALUES
    (2001, 101, 1001, 1, 'src/webhook.py', 73,
     'Reject an empty signature header.', TRUE, TRUE, now()),
    (2002, 101, NULL, 2, 'docs/security.md', NULL,
     'Document key rotation behavior.', FALSE, FALSE, NULL),
    (2003, 102, 1003, 1, 'src/invoices.py', 118,
     'Include the query plan in the review description.', TRUE, FALSE, NULL);

INSERT INTO status_checks (
    pull_request_id, check_name, commit_sha, state, details, completed_at
)
VALUES
    (101, 'unit-tests', 'head-101', 'SUCCESS', 'All unit tests passed.', now()),
    (101, 'security-scan', 'head-101', 'SUCCESS', 'No blocking findings.', now()),
    (102, 'unit-tests', 'head-102', 'IN_PROGRESS', 'Test suite is running.', NULL);

-- The first PR has approvals and passing checks, but an unresolved conversation.
SELECT * FROM pull_request_merge_eligibility ORDER BY number;

-- Computed properties are represented by query expressions rather than
-- stored duplicate fields.
SELECT
    r.owner || '/' || r.name AS full_name,
    b.name AS branch_name,
    b.head_sha,
    bp.required_approvals,
    bp.restrict_direct_pushes
FROM repositories r
JOIN branches b ON b.repository_id = r.repository_id
LEFT JOIN branch_protection bp
  ON bp.repository_id = r.repository_id
 AND bp.branch_name = b.name
ORDER BY r.name, b.name;

-- The latest review per reviewer determines the current decision.
SELECT DISTINCT ON (rv.username)
    rv.username,
    re.state,
    re.commit_sha,
    re.submitted_at
FROM reviews re
JOIN reviewers rv ON rv.reviewer_id = re.reviewer_id
WHERE re.pull_request_id = 101
ORDER BY rv.username, re.submitted_at DESC, re.review_id DESC;

-- Resolve the outstanding conversation and evaluate eligibility again.
UPDATE review_comments
SET resolved = TRUE,
    resolved_at = now()
WHERE comment_id = 2002;

SELECT * FROM pull_request_merge_eligibility WHERE number = 101;

-- A new head commit makes earlier approvals stale under this policy.
UPDATE pull_requests
SET head_sha = 'head-103',
    updated_at = now()
WHERE pull_request_id = 101;

SELECT * FROM pull_request_merge_eligibility WHERE number = 101;

-- Record new decisions for the new source commit.
INSERT INTO reviews (
    review_id, pull_request_id, reviewer_id, state, commit_sha, body
)
VALUES
    (1004, 101, 1, 'APPROVED', 'head-103', 'Reviewed the updated source commit.'),
    (1005, 101, 2, 'APPROVED', 'head-103', 'Updated change is acceptable.');

INSERT INTO status_checks (
    pull_request_id, check_name, commit_sha, state, details, completed_at
)
VALUES
    (101, 'unit-tests', 'head-103', 'SUCCESS', 'Updated test suite passed.', now()),
    (101, 'security-scan', 'head-103', 'SUCCESS', 'Updated security scan passed.', now());

SELECT * FROM pull_request_merge_eligibility WHERE number = 101;

-- The trigger prevents direct modification of a protected branch head.
-- Run this statement separately if you want to observe the expected error:
-- UPDATE branches SET head_sha = 'unauthorized-head'
-- WHERE repository_id = 1 AND name = 'main';

COMMIT;
