"""
CSS Cascade: Cascade, Inheritance, Specificity, Source Order, !important,
and Debugging Styles

This standalone study script teaches the CSS cascade from beginner to advanced
level by implementing a small CSS cascade engine in Python.

The program does not require external packages. It models:
- CSS declarations
- selectors
- specificity
- source order
- inheritance
- !important
- inline styles
- CSS-wide keywords
- custom properties
- debugging and explanation of winning declarations
- performance considerations
- realistic component styling

The implementation is intentionally simplified compared with a browser's full
CSS engine. A real browser also considers origins, layers, pseudo-elements,
pseudo-classes, media queries, container queries, animations, transitions,
shadow DOM, and property-specific inheritance behavior.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import re


# ---------------------------------------------------------------------------
# 1. Fundamental terminology
# ---------------------------------------------------------------------------
#
# CSS declaration:
#     color: blue;
#
# Property:
#     color
#
# Value:
#     blue
#
# Rule:
#     .button { color: blue; }
#
# Selector:
#     .button
#
# Specificity:
#     A tuple describing how strongly a selector targets an element.
#
# Cascade:
#     The browser's process for deciding which applicable declaration wins
#     when multiple declarations target the same property.
#
# Inheritance:
#     The mechanism by which some properties obtain their value from an
#     ancestor when the element does not establish its own value.
#
# Source order:
#     When otherwise relevant cascade factors tie, the later declaration wins.
#
# !important:
#     Changes the cascade priority of a declaration. It should be used
#     sparingly because it makes normal overrides more difficult.


# ---------------------------------------------------------------------------
# 2. Data structures
# ---------------------------------------------------------------------------

@dataclass
class Element:
    tag: str
    element_id: Optional[str] = None
    classes: List[str] = field(default_factory=list)
    attributes: Dict[str, str] = field(default_factory=dict)
    parent: Optional["Element"] = None
    children: List["Element"] = field(default_factory=list)
    inline_styles: Dict[str, str] = field(default_factory=dict)

    def add_child(self, child: "Element") -> None:
        child.parent = self
        self.children.append(child)

    def description(self) -> str:
        result = self.tag
        if self.element_id:
            result += f"#{self.element_id}"
        for class_name in self.classes:
            result += f".{class_name}"
        return result


@dataclass
class CSSDeclaration:
    property_name: str
    value: str
    important: bool = False
    source_order: int = 0
    origin: str = "author"
    selector: str = ""
    specificity: Tuple[int, int, int] = (0, 0, 0)

    def priority_key(self) -> Tuple[int, int, int, int, int, int, int]:
        """
        A teaching-oriented cascade key.

        The real CSS cascade has more dimensions than this simplified model.
        Here we compare:
        1. importance
        2. origin
        3. specificity
        4. source order

        Inline styles receive a separate specificity-like treatment when
        generated by the resolver.
        """
        importance_rank = 1 if self.important else 0

        origin_rank = {
            "user-agent": 0,
            "user": 1,
            "author": 2,
        }.get(self.origin, 2)

        a, b, c = self.specificity

        return (
            importance_rank,
            origin_rank,
            a,
            b,
            c,
            self.source_order,
            0,
        )


@dataclass
class Rule:
    selector: str
    declarations: List[CSSDeclaration]
    source_order: int


@dataclass
class Candidate:
    declaration: CSSDeclaration
    matched: bool
    reason: str


# ---------------------------------------------------------------------------
# 3. Specificity
# ---------------------------------------------------------------------------

def calculate_specificity(selector: str) -> Tuple[int, int, int]:
    """
    Calculate simplified CSS specificity.

    Specificity is commonly represented as:

        (ID, class/attribute/pseudo-class, type/pseudo-element)

    Examples:
        p             -> (0, 0, 1)
        .card         -> (0, 1, 0)
        #main         -> (1, 0, 0)
        #main .card p -> (1, 1, 1)

    This function intentionally does not implement every modern selector
    exception such as :where(), :is(), :not(), nesting, or selector lists.
    """

    selector_without_strings = re.sub(r'"[^"]*"|\'[^\']*\'', "", selector)

    ids = len(re.findall(r"#[A-Za-z_][\w-]*", selector_without_strings))

    classes = len(re.findall(r"\.[A-Za-z_][\w-]*", selector_without_strings))

    attributes = len(
        re.findall(r"\[[^\]]+\]", selector_without_strings)
    )

    pseudo_classes = len(
        re.findall(
            r":(?!:)[A-Za-z_-][\w-]*(?:\([^)]*\))?",
            selector_without_strings,
        )
    )

    pseudo_elements = len(
        re.findall(r"::[A-Za-z_-][\w-]*", selector_without_strings)
    )

    # Remove IDs, classes, attributes, pseudo selectors and universal
    # selectors before estimating type-selector count.
    simplified = re.sub(
        r"#[A-Za-z_][\w-]*"
        r"|\.[A-Za-z_][\w-]*"
        r"\[[^\]]+\]"
        r"|::?[A-Za-z_-][\w-]*(?:\([^)]*\))?",
        " ",
        selector_without_strings,
    )

    type_names = re.findall(
        r"(?<![-\w])[A-Za-z][A-Za-z0-9_-]*", simplified
    )

    # Common combinators and CSS keywords are not type selectors.
    ignored = {
        "and",
        "or",
        "not",
        "where",
        "is",
    }

    type_count = sum(
        1 for name in type_names if name.lower() not in ignored
    )

    type_count += pseudo_elements

    return (
        ids,
        classes + attributes + pseudo_classes,
        type_count,
    )


# ---------------------------------------------------------------------------
# 4. Selector matching
# ---------------------------------------------------------------------------

def simple_selector_matches(element: Element, selector: str) -> bool:
    """
    Match a basic compound selector.

    Supported examples:
        div
        .card
        #main
        div.card
        div#main.card
        [data-state="active"]
        [data-state]

    The implementation is deliberately educational rather than a complete
    CSS selector engine.
    """

    selector = selector.strip()

    if not selector:
        return False

    if ":" in selector:
        # Pseudo-classes are outside this small matching engine.
        selector = selector.split(":", 1)[0]

    selector = selector.replace("::before", "").strip()

    if not selector:
        return True

    tag_match = re.match(r"^[A-Za-z][A-Za-z0-9_-]*|\*", selector)

    if tag_match:
        tag = tag_match.group(0)
        if tag != "*" and element.tag.lower() != tag.lower():
            return False

    for element_id in re.findall(r"#([A-Za-z_][\w-]*)", selector):
        if element.element_id != element_id:
            return False

    for class_name in re.findall(r"\.([A-Za-z_][\w-]*)", selector):
        if class_name not in element.classes:
            return False

    for attribute_expression in re.findall(
        r"\[([^\]]+)\]", selector
    ):
        expression = attribute_expression.strip()

        if "=" in expression:
            attribute_name, expected = expression.split("=", 1)
            attribute_name = attribute_name.strip()
            expected = expected.strip().strip("\"'")
            if element.attributes.get(attribute_name) != expected:
                return False
        else:
            if expression not in element.attributes:
                return False

    return True


def selector_matches(element: Element, selector: str) -> bool:
    """
    Support basic descendant and child combinators.

    Examples:
        .card .title
        .card > .title
        main .button

    This is enough to demonstrate why a declaration may or may not participate
    in the cascade.
    """

    selector = selector.strip()

    if ">" in selector:
        left, right = selector.rsplit(">", 1)
        if not simple_selector_matches(element, right.strip()):
            return False

        if element.parent is None:
            return False

        return selector_matches(element.parent, left.strip())

    parts = selector.split()

    if len(parts) == 1:
        return simple_selector_matches(element, parts[0])

    if not simple_selector_matches(element, parts[-1]):
        return False

    ancestor = element.parent

    for part in reversed(parts[:-1]):
        found = False

        while ancestor is not None:
            if simple_selector_matches(ancestor, part):
                found = True
                ancestor = ancestor.parent
                break
            ancestor = ancestor.parent

        if not found:
            return False

    return True


# ---------------------------------------------------------------------------
# 5. CSS-wide keywords and inheritance
# ---------------------------------------------------------------------------

INHERITED_PROPERTIES = {
    "color",
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
    "text-align",
    "visibility",
    "cursor",
}

INITIAL_VALUES = {
    "color": "black",
    "background-color": "transparent",
    "font-size": "medium",
    "font-weight": "normal",
    "display": "inline",
    "margin": "0",
    "padding": "0",
    "border": "none",
    "opacity": "1",
}


def is_inherited_property(property_name: str) -> bool:
    return property_name.lower() in INHERITED_PROPERTIES


# ---------------------------------------------------------------------------
# 6. Cascade engine
# ---------------------------------------------------------------------------

class CSSCascadeEngine:
    def __init__(self, rules: List[Rule]):
        self.rules = rules

    def declarations_for(
        self,
        element: Element,
        property_name: str,
    ) -> List[CSSDeclaration]:
        candidates: List[CSSDeclaration] = []

        for rule in self.rules:
            if not selector_matches(element, rule.selector):
                continue

            for declaration in rule.declarations:
                if declaration.property_name == property_name:
                    candidates.append(declaration)

        # Inline styles are represented as an author declaration with an
        # extremely strong specificity component.
        if property_name in element.inline_styles:
            raw_value = element.inline_styles[property_name]
            important = raw_value.strip().endswith("!important")

            if important:
                raw_value = raw_value.replace("!important", "").strip()

            candidates.append(
                CSSDeclaration(
                    property_name=property_name,
                    value=raw_value,
                    important=important,
                    source_order=10_000_000,
                    origin="author",
                    selector="style attribute",
                    specificity=(1, 0, 0),
                )
            )

        return candidates

    def resolve(
        self,
        element: Element,
        property_name: str,
        trace: bool = False,
    ) -> Tuple[str, List[Candidate]]:
        candidates = self.declarations_for(element, property_name)

        candidate_records: List[Candidate] = []

        for declaration in candidates:
            candidate_records.append(
                Candidate(
                    declaration=declaration,
                    matched=True,
                    reason="Selector matched the element.",
                )
            )

        if candidates:
            winner = max(
                candidates,
                key=lambda declaration: declaration.priority_key()
            )

            value = winner.value.strip()

            # CSS-wide keywords.
            if value == "inherit":
                if element.parent:
                    inherited_value, _ = self.resolve(
                        element.parent,
                        property_name,
                        trace=False,
                    )
                    return inherited_value, candidate_records
                return INITIAL_VALUES.get(property_name, "initial"), candidate_records

            if value == "initial":
                return INITIAL_VALUES.get(property_name, "initial"), candidate_records

            if value == "unset":
                if is_inherited_property(property_name) and element.parent:
                    inherited_value, _ = self.resolve(
                        element.parent,
                        property_name,
                        trace=False,
                    )
                    return inherited_value, candidate_records
                return INITIAL_VALUES.get(property_name, "initial"), candidate_records

            if value == "revert":
                # A complete browser implementation would revert to the
                # previous cascade origin/layer. We model it as initial here.
                return INITIAL_VALUES.get(property_name, "initial"), candidate_records

            return value, candidate_records

        # No declaration won. Inherited properties look to the parent.
        if is_inherited_property(property_name) and element.parent:
            inherited_value, _ = self.resolve(
                element.parent,
                property_name,
                trace=False,
            )
            return inherited_value, candidate_records

        return INITIAL_VALUES.get(property_name, "initial"), candidate_records

    def explain(
        self,
        element: Element,
        property_name: str,
    ) -> None:
        value, candidates = self.resolve(
            element,
            property_name,
            trace=True,
        )

        print(f"\nProperty: {property_name}")
        print(f"Element:  {element.description()}")
        print(f"Final:    {value}")

        if not candidates:
            if is_inherited_property(property_name) and element.parent:
                print("Reason:   No local declaration; value comes through inheritance.")
            else:
                print("Reason:   No matching declaration; initial value is used.")
            return

        print("\nCascade candidates:")

        ordered = sorted(
            candidates,
            key=lambda candidate: candidate.declaration.priority_key(),
            reverse=True,
        )

        for index, candidate in enumerate(ordered):
            declaration = candidate.declaration

            status = "WINNER" if index == 0 else "loser"

            print(
                f"  {status:7} "
                f"{declaration.selector:20} "
                f"{declaration.property_name}: "
                f"{declaration.value}"
                f"{' !important' if declaration.important else ''} "
                f"specificity={declaration.specificity} "
                f"order={declaration.source_order}"
            )


# ---------------------------------------------------------------------------
# 7. Rule construction helper
# ---------------------------------------------------------------------------

def make_rule(
    selector: str,
    declarations: Dict[str, str],
    source_order: int,
) -> Rule:
    specificity = calculate_specificity(selector)

    css_declarations = []

    for property_name, raw_value in declarations.items():
        value = raw_value.strip()

        important = False

        if value.endswith("!important"):
            important = True
            value = value[:-10].strip()

        css_declarations.append(
            CSSDeclaration(
                property_name=property_name,
                value=value,
                important=important,
                source_order=source_order,
                selector=selector,
                specificity=specificity,
            )
        )

    return Rule(
        selector=selector,
        declarations=css_declarations,
        source_order=source_order,
    )


# ---------------------------------------------------------------------------
# 8. Beginner example: source order
# ---------------------------------------------------------------------------

def example_source_order() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 1: SOURCE ORDER")
    print("=" * 72)

    rules = [
        make_rule(".button", {"color": "blue"}, 1),
        make_rule(".button", {"color": "green"}, 2),
    ]

    button = Element(
        tag="button",
        classes=["button"],
    )

    engine = CSSCascadeEngine(rules)

    value, _ = engine.resolve(button, "color")

    print("Two rules have identical selectors and specificity.")
    print("The later declaration wins.")
    print(f"Result: {value}")

    engine.explain(button, "color")


# ---------------------------------------------------------------------------
# 9. Specificity comparison
# ---------------------------------------------------------------------------

def example_specificity() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 2: SPECIFICITY")
    print("=" * 72)

    selectors = [
        "p",
        ".card",
        "#main",
        "div.card",
        "#main .card",
        "main article.card p",
        "[data-state='active']",
    ]

    for selector in selectors:
        print(
            f"{selector:30} -> "
            f"{calculate_specificity(selector)}"
        )

    rules = [
        make_rule("p", {"color": "black"}, 1),
        make_rule(".message", {"color": "blue"}, 2),
        make_rule("#warning", {"color": "red"}, 3),
    ]

    paragraph = Element(
        tag="p",
        element_id="warning",
        classes=["message"],
    )

    engine = CSSCascadeEngine(rules)

    value, _ = engine.resolve(paragraph, "color")

    print(f"\nFinal color: {value}")
    print("The ID selector has greater specificity than the class and type selectors.")

    engine.explain(paragraph, "color")


# ---------------------------------------------------------------------------
# 10. !important
# ---------------------------------------------------------------------------

def example_important() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 3: !IMPORTANT")
    print("=" * 72)

    rules = [
        make_rule("#dashboard .button", {"color": "red"}, 1),
        make_rule(".button", {"color": "blue !important"}, 2),
    ]

    button = Element(
        tag="button",
        classes=["button"],
    )

    dashboard = Element(
        tag="div",
        element_id="dashboard",
    )

    dashboard.add_child(button)

    engine = CSSCascadeEngine(rules)

    value, _ = engine.resolve(button, "color")

    print(f"Final color: {value}")
    print(
        "The normal declaration has higher specificity, "
        "but the !important declaration enters the important cascade."
    )

    engine.explain(button, "color")


# ---------------------------------------------------------------------------
# 11. Inheritance
# ---------------------------------------------------------------------------

def example_inheritance() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 4: INHERITANCE")
    print("=" * 72)

    body = Element(tag="body")
    article = Element(tag="article")
    heading = Element(tag="h1")

    body.add_child(article)
    article.add_child(heading)

    rules = [
        make_rule("body", {"color": "darkslategray"}, 1),
        make_rule("article", {"font-family": "Arial"}, 2),
    ]

    engine = CSSCascadeEngine(rules)

    color, _ = engine.resolve(heading, "color")
    font_family, _ = engine.resolve(heading, "font-family")
    display, _ = engine.resolve(heading, "display")

    print(f"h1 color:        {color}")
    print(f"h1 font-family:  {font_family}")
    print(f"h1 display:      {display}")

    print(
        "\nColor and font-family are inherited properties in this model. "
        "display uses its own initial value when no declaration applies."
    )


# ---------------------------------------------------------------------------
# 12. Explicit inheritance keywords
# ---------------------------------------------------------------------------

def example_css_wide_keywords() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 5: CSS-WIDE KEYWORDS")
    print("=" * 72)

    parent = Element(tag="div")
    child = Element(tag="span")
    parent.add_child(child)

    rules = [
        make_rule("div", {"color": "purple"}, 1),
        make_rule("span", {"color": "inherit"}, 2),
    ]

    engine = CSSCascadeEngine(rules)

    print("inherit  ->", engine.resolve(child, "color")[0])

    rules = [
        make_rule("div", {"color": "purple"}, 1),
        make_rule("span", {"color": "initial"}, 2),
    ]

    engine = CSSCascadeEngine(rules)

    print("initial  ->", engine.resolve(child, "color")[0])

    rules = [
        make_rule("div", {"color": "purple"}, 1),
        make_rule("span", {"color": "unset"}, 2),
    ]

    engine = CSSCascadeEngine(rules)

    print("unset    ->", engine.resolve(child, "color")[0])


# ---------------------------------------------------------------------------
# 13. Inline styles
# ---------------------------------------------------------------------------

def example_inline_style() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 6: INLINE STYLES")
    print("=" * 72)

    button = Element(
        tag="button",
        classes=["button"],
        inline_styles={"color": "orange"},
    )

    rules = [
        make_rule(".button", {"color": "blue"}, 1),
        make_rule("#save", {"color": "red"}, 2),
    ]

    button.element_id = "save"

    engine = CSSCascadeEngine(rules)

    value, _ = engine.resolve(button, "color")

    print(f"Result: {value}")
    print(
        "Inline author styles normally outrank ordinary selector-based "
        "author declarations because of their special cascade position."
    )

    engine.explain(button, "color")


# ---------------------------------------------------------------------------
# 14. Practical debugging workflow
# ---------------------------------------------------------------------------

def debug_workflow() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 7: DEBUGGING A STYLE CONFLICT")
    print("=" * 72)

    rules = [
        make_rule(".card", {"color": "black"}, 1),
        make_rule(".card .title", {"color": "navy"}, 2),
        make_rule("#featured .title", {"color": "purple"}, 3),
        make_rule(".title", {"color": "orange !important"}, 4),
    ]

    featured = Element(
        tag="section",
        element_id="featured",
    )

    title = Element(
        tag="h2",
        classes=["card", "title"],
    )

    featured.add_child(title)

    engine = CSSCascadeEngine(rules)

    engine.explain(title, "color")

    print(
        "\nDebugging checklist:"
        "\n1. Confirm that the expected element is selected."
        "\n2. Inspect matching selectors."
        "\n3. Check declarations crossed out by DevTools."
        "\n4. Compare !important status."
        "\n5. Compare specificity."
        "\n6. Compare source order when specificity ties."
        "\n7. Check inheritance from ancestors."
        "\n8. Check browser defaults and user-agent styles."
        "\n9. Check media/container queries."
        "\n10. Check whether a CSS custom property resolves to the expected value."
    )


# ---------------------------------------------------------------------------
# 15. Common specificity trap
# ---------------------------------------------------------------------------

def specificity_trap() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 8: THE SPECIFICITY TRAP")
    print("=" * 72)

    rules = [
        make_rule(".navigation .item", {"color": "blue"}, 1),
        make_rule(".item", {"color": "red"}, 2),
        make_rule(".item", {"color": "green"}, 3),
    ]

    item = Element(
        tag="a",
        classes=["item"],
    )

    navigation = Element(
        tag="nav",
        classes=["navigation"],
    )

    navigation.add_child(item)

    engine = CSSCascadeEngine(rules)

    print(
        "The later .item rule does not beat .navigation .item "
        "because specificity differs."
    )

    engine.explain(item, "color")


# ---------------------------------------------------------------------------
# 16. Simulating a small design system
# ---------------------------------------------------------------------------

def design_system_example() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 9: COMPONENT DESIGN SYSTEM")
    print("=" * 72)

    rules = [
        make_rule(
            ":root",
            {
                "--brand-color": "#2457d6",
                "--surface": "#ffffff",
            },
            1,
        ),
        make_rule(
            ".button",
            {
                "color": "white",
                "background-color": "var(--brand-color)",
                "padding": "0.75rem 1rem",
            },
            2,
        ),
        make_rule(
            ".button.secondary",
            {
                "color": "black",
                "background-color": "#eeeeee",
            },
            3,
        ),
        make_rule(
            ".button.disabled",
            {
                "opacity": "0.5",
                "cursor": "not-allowed",
            },
            4,
        ),
    ]

    secondary_button = Element(
        tag="button",
        classes=["button", "secondary"],
    )

    engine = CSSCascadeEngine(rules)

    for property_name in [
        "color",
        "background-color",
        "padding",
        "opacity",
        "cursor",
    ]:
        value, _ = engine.resolve(
            secondary_button,
            property_name,
        )
        print(f"{property_name:20} -> {value}")

    print(
        "\nThe cascade is especially useful in component systems where "
        "base styles establish defaults and modifier classes override "
        "specific properties."
    )


# ---------------------------------------------------------------------------
# 17. A custom-property resolver
# ---------------------------------------------------------------------------

CUSTOM_PROPERTY_PATTERN = re.compile(
    r"var\(\s*(--[A-Za-z0-9_-]+)"
    r"(?:\s*,\s*([^()]+))?\s*\)"
)


def collect_custom_properties(
    engine: CSSCascadeEngine,
    element: Element,
) -> Dict[str, str]:
    """
    Collect custom properties visible to an element.

    Custom properties inherit by default, which makes them useful for
    component-level theming.
    """
    result: Dict[str, str] = {}

    if element.parent is not None:
        result.update(
            collect_custom_properties(engine, element.parent)
        )

    for rule in engine.rules:
        if selector_matches(element, rule.selector):
            for declaration in rule.declarations:
                if declaration.property_name.startswith("--"):
                    result[declaration.property_name] = declaration.value

    for name, value in element.inline_styles.items():
        if name.startswith("--"):
            result[name] = value

    return result


def resolve_custom_properties(
    value: str,
    custom_properties: Dict[str, str],
    max_depth: int = 20,
) -> str:
    """
    Resolve simple var() expressions.

    A browser performs more sophisticated token-level processing. This helper
    exists to demonstrate the conceptual relationship between custom
    properties and the cascade.
    """

    result = value

    for _ in range(max_depth):
        match = CUSTOM_PROPERTY_PATTERN.search(result)

        if not match:
            return result

        name = match.group(1)
        fallback = match.group(2)

        if name in custom_properties:
            replacement = custom_properties[name]
        elif fallback is not None:
            replacement = fallback.strip()
        else:
            raise ValueError(
                f"Undefined custom property: {name}"
            )

        result = result[:match.start()] + replacement + result[match.end():]

    raise ValueError("Too many nested var() references")


def custom_property_example() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 10: CUSTOM PROPERTIES AND THE CASCADE")
    print("=" * 72)

    rules = [
        make_rule(
            ":root",
            {"--brand": "royalblue"},
            1,
        ),
        make_rule(
            ".dark",
            {"--brand": "lightblue"},
            2,
        ),
        make_rule(
            ".button",
            {"color": "var(--brand)"},
            3,
        ),
    ]

    root = Element(
        tag="div",
        classes=["dark"],
    )

    button = Element(
        tag="button",
        classes=["button"],
    )

    root.add_child(button)

    engine = CSSCascadeEngine(rules)

    raw_value, _ = engine.resolve(button, "color")
    variables = collect_custom_properties(engine, button)

    try:
        final_value = resolve_custom_properties(
            raw_value,
            variables,
        )
    except ValueError as error:
        final_value = f"ERROR: {error}"

    print("Raw color:", raw_value)
    print("Variables:", variables)
    print("Resolved color:", final_value)


# ---------------------------------------------------------------------------
# 18. CSS architecture and maintainability
# ---------------------------------------------------------------------------

def architecture_guidance() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 11: MAINTAINABLE CASCADE")
    print("=" * 72)

    guidance = {
        "Prefer classes": (
            "Classes usually provide reusable, predictable specificity."
        ),
        "Keep specificity low": (
            "Low specificity makes components easier to override."
        ),
        "Avoid unnecessary IDs": (
            "IDs create strong selectors that can produce override problems."
        ),
        "Limit !important": (
            "Important declarations can make normal component composition harder."
        ),
        "Use layers deliberately": (
            "Modern CSS layers provide explicit ordering between groups of rules."
        ),
        "Debug the winner": (
            "Find the winning declaration before changing random selectors."
        ),
    }

    for principle, explanation in guidance.items():
        print(f"{principle}: {explanation}")


# ---------------------------------------------------------------------------
# 19. Performance considerations
# ---------------------------------------------------------------------------

def performance_notes() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 12: PERFORMANCE CONSIDERATIONS")
    print("=" * 72)

    print(
        "Selector matching is part of browser style calculation."
    )
    print(
        "Very large stylesheets, excessive DOM complexity, frequent DOM "
        "changes, and style-dependent layout work can increase rendering cost."
    )
    print(
        "Practical principles:"
    )
    print(
        "  - Prefer understandable selectors over clever selector chains."
    )
    print(
        "  - Avoid unnecessary deeply nested selectors."
    )
    print(
        "  - Batch DOM changes when possible."
    )
    print(
        "  - Avoid repeatedly forcing synchronous layout measurements."
    )
    print(
        "  - Use browser performance tools to identify real bottlenecks."
    )


# ---------------------------------------------------------------------------
# 20. Testing cascade behavior
# ---------------------------------------------------------------------------

def assert_equal(actual, expected, description):
    if actual != expected:
        raise AssertionError(
            f"{description}: expected {expected!r}, got {actual!r}"
        )


def run_tests() -> None:
    print("\n" + "=" * 72)
    print("TESTS")
    print("=" * 72)

    # Equal specificity: later wins.
    rules = [
        make_rule(".box", {"color": "red"}, 1),
        make_rule(".box", {"color": "blue"}, 2),
    ]
    element = Element(tag="div", classes=["box"])
    engine = CSSCascadeEngine(rules)
    assert_equal(
        engine.resolve(element, "color")[0],
        "blue",
        "Source order",
    )

    # Specificity beats source order.
    rules = [
        make_rule(".box", {"color": "red"}, 1),
        make_rule("div.box", {"color": "blue"}, 2),
    ]
    engine = CSSCascadeEngine(rules)
    assert_equal(
        engine.resolve(element, "color")[0],
        "blue",
        "Specificity",
    )

    # Important declaration beats normal declaration.
    rules = [
        make_rule("#main .box", {"color": "red"}, 2),
        make_rule(".box", {"color": "green !important"}, 1),
    ]

    main = Element(tag="div", element_id="main")
    main.add_child(element)

    engine = CSSCascadeEngine(rules)

    assert_equal(
        engine.resolve(element, "color")[0],
        "green",
        "!important",
    )

    # Inheritance.
    parent = Element(tag="div")
    child = Element(tag="span")
    parent.add_child(child)

    rules = [
        make_rule("div", {"color": "purple"}, 1),
    ]

    engine = CSSCascadeEngine(rules)

    assert_equal(
        engine.resolve(child, "color")[0],
        "purple",
        "Inheritance",
    )

    print("All tests passed.")


# ---------------------------------------------------------------------------
# 21. Real-world component scenario
# ---------------------------------------------------------------------------

def real_world_scenario() -> None:
    print("\n" + "=" * 72)
    print("EXAMPLE 13: REAL-WORLD PRODUCT CARD")
    print("=" * 72)

    page = Element(
        tag="main",
        classes=["product-page"],
    )

    card = Element(
        tag="article",
        classes=["product-card", "featured"],
        attributes={"data-state": "active"},
    )

    title = Element(
        tag="h2",
        classes=["product-title"],
    )

    price = Element(
        tag="span",
        classes=["price"],
    )

    page.add_child(card)
    card.add_child(title)
    card.add_child(price)

    rules = [
        make_rule(
            ".product-card",
            {
                "color": "black",
                "background-color": "white",
            },
            1,
        ),
        make_rule(
            ".product-card.featured",
            {
                "background-color": "lightyellow",
            },
            2,
        ),
        make_rule(
            ".product-card .product-title",
            {
                "color": "darkblue",
                "font-size": "1.5rem",
            },
            3,
        ),
        make_rule(
            "[data-state='active'] .price",
            {
                "color": "green",
                "font-weight": "bold",
            },
            4,
        ),
        make_rule(
            ".product-page",
            {
                "font-family": "Arial",
                "color": "slategray",
            },
            5,
        ),
    ]

    engine = CSSCascadeEngine(rules)

    for element in [card, title, price]:
        print(f"\n{element.description()}")

        for property_name in [
            "color",
            "background-color",
            "font-family",
            "font-size",
            "font-weight",
        ]:
            value, _ = engine.resolve(
                element,
                property_name,
            )
            print(f"  {property_name:18} {value}")

    print(
        "\nNotice how a child may inherit color or font-family while "
        "its own declarations control properties such as font-size."
    )


# ---------------------------------------------------------------------------
# 22. Advanced cascade concepts
# ---------------------------------------------------------------------------

def advanced_concepts() -> None:
    print("\n" + "=" * 72)
    print("ADVANCED CONCEPTS")
    print("=" * 72)

    concepts = [
        (
            "Cascade origins",
            "User-agent, user, and author styles participate in the cascade."
        ),
        (
            "Cascade layers",
            "Modern CSS can group declarations into explicit @layer ordering."
        ),
        (
            "Pseudo-classes",
            ":hover, :focus, :disabled and similar states can change matching."
        ),
        (
            "Media queries",
            "A declaration may apply only when a media condition is true."
        ),
        (
            "Container queries",
            "Styles can respond to an ancestor container's size or conditions."
        ),
        (
            "Animations",
            "Animated values interact with the cascade differently from ordinary declarations."
        ),
        (
            "Transitions",
            "Transitions can temporarily produce values between states."
        ),
        (
            "Shadow DOM",
            "Encapsulation changes how selectors and inheritance cross component boundaries."
        ),
        (
            "CSS nesting",
            "Nested rules provide structured relationships while still participating in the cascade."
        ),
        (
            ":where()",
            "Its arguments contribute zero specificity."
        ),
        (
            ":is() and :not()",
            "Their specificity follows special modern selector rules."
        ),
    ]

    for name, description in concepts:
        print(f"{name}: {description}")


# ---------------------------------------------------------------------------
# 23. Common mistakes
# ---------------------------------------------------------------------------

def common_mistakes() -> None:
    print("\n" + "=" * 72)
    print("COMMON MISTAKES")
    print("=" * 72)

    mistakes = [
        "Assuming the last rule always wins.",
        "Ignoring specificity.",
        "Using !important to fix every conflict.",
        "Confusing inheritance with the cascade.",
        "Forgetting browser user-agent styles.",
        "Debugging the wrong element.",
        "Assuming every CSS property inherits.",
        "Using IDs unnecessarily for reusable components.",
        "Creating selectors that are unnecessarily deep.",
        "Changing specificity repeatedly instead of identifying the actual winner.",
        "Ignoring media queries or state selectors.",
        "Assuming a custom property is automatically defined everywhere.",
    ]

    for number, mistake in enumerate(mistakes, 1):
        print(f"{number:2}. {mistake}")


# ---------------------------------------------------------------------------
# 24. Educational cascade algorithm
# ---------------------------------------------------------------------------

def summarize_cascade_process() -> None:
    print("\n" + "=" * 72)
    print("CASCADE ALGORITHM: CONCEPTUAL VIEW")
    print("=" * 72)

    stages = [
        "1. Identify the element and requested property.",
        "2. Find declarations whose selectors match the element.",
        "3. Remove declarations that do not apply because their conditions fail.",
        "4. Consider cascade origin and importance.",
        "5. Compare cascade layers when layers are involved.",
        "6. Compare specificity.",
        "7. Compare source order when the earlier factors tie.",
        "8. Resolve CSS-wide keywords and custom properties.",
        "9. If appropriate, obtain the value through inheritance.",
        "10. Fall back to the property's initial or other applicable value.",
        "11. The resulting computed value participates in later rendering stages.",
    ]

    for stage in stages:
        print(stage)


# ---------------------------------------------------------------------------
# 25. Main program
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 72)
    print("CSS CASCADE STUDY PROGRAM")
    print("=" * 72)
    print(
        "Topic: cascade, inheritance, specificity, source order, "
        "!important, and debugging styles"
    )

    example_source_order()
    example_specificity()
    example_important()
    example_inheritance()
    example_css_wide_keywords()
    example_inline_style()
    debug_workflow()
    specificity_trap()
    design_system_example()
    custom_property_example()
    architecture_guidance()
    performance_notes()
    real_world_scenario()
    advanced_concepts()
    common_mistakes()
    summarize_cascade_process()
    run_tests()

    print("\n" + "=" * 72)
    print("PROGRAM COMPLETE")
    print("=" * 72)


if __name__ == "__main__":
    main()
